- name: "Prepare CDM server"
  hosts: server
  tags:
    - server
    - never
  vars: 
    install_cdm: true
  vars_files:
    - ./vars.yml
  roles:
    - cdm

- name: "Install CDM server"
  hosts: server
  tags:
    - server
    - never
  serial: 1
  vars:
    init_cdm: true
  vars_files:
    - ./vars.yml
  roles:
    - cdm


- name: "Install CDM client"
  hosts: client
  tags:
    - client
    - never
  vars:
    install_client: true
  vars_files:
    - ./vars.yml
  roles:
    - cdm

- name: "Uninstall CDM server"
  hosts: server
  tags:
    - uninstall
    - never
  serial: 1
  vars:
    uninstall_cdm: true
  vars_files:
    - ./vars.yml
  roles:
    - cdm

- name: "Uninstall CDM client"
  hosts: client
  tags:
    - uninstallclient
    - never
  vars:
    uninstall_client: true
  vars_files:
    - ./vars.yml
  roles:
    - cdm

- name: "Patch CDM server"
  hosts: server
  tags:
    - patch
    - never
  vars:
    patch_cdm: true
  vars_files:
    - ./vars.yml
  roles:
    - cdm
