- name: "Prepare CDM7.0"
  hosts: vms
  vars: 
    install_cdm: true
  vars_files:
    - ./vars.yml
  roles:
    - cdm

- name: "Install CDM7.0"
  hosts: vms
  serial: 1
  vars:
    init_cdm: true
  vars_files:
    - ./vars.yml
  roles:
    - cdm
