- hosts: vms
#  user: root
  gather_facts: no
  tasks:
    - name: close ssh check
      shell: sed -i "s/^.*StrictHostKeyChecking.*$/ StrictHostKeyChecking no/g" /etc/ssh/ssh_config /etc/ssh/ssh_config
    - name: ssh-copy
      authorized_key: user=root key="{{lookup('file','/root/.ssh/id_rsa.pub')}}"
      tags:
        - sshkey
